version: 0.0
os: linux
files: # source to destination
  - source: /
    destination: /home/ec2-user/product-search-server/deploy/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user
