name: Gaejangmo product search api continuous deploy

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build


    - name: Zip for deploy
      run: |
        mkdir -p before-deploy/
        cp appspec/scripts/*sh before-deploy/
        cp appspec/appspec.yml before-deploy/
        cp build/libs/* before-deploy/
        cd before-deploy && zip -r product-search-api.zip *
        cd ../ && mkdir -p deploy
        mv before-deploy/product-search-api.zip deploy/product-search-api.zip
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        AWS-ACCESS-KEY-ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS-SECRET-ACCESS-KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS-REGION: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 deploy/product-search-api.zip s3://gae-jang-mo-deploy/product-search-api.zip

    - name: Code Deploy
      run: |
        aws deploy create-deployment \
        --application-name gae-jang-mo \
        --deployment-config-name CodeDeployDefault.OneAtATime \
        --deployment-group-name deploy \
        --s3-location bucket=gae-jang-mo-deploy,bundleType=zip,key=product-search-api.zip
